import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ContentGen",
  description: "Auto-generated posts by the ContentGen agent",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-neutral-50 text-neutral-900">
        <header className="border-b bg-white">
          <div className="mx-auto max-w-3xl px-4 py-4 flex items-center justify-between">
            <Link href="/" className="font-semibold">ContentGen</Link>
            <nav className="text-sm text-neutral-600">
              <Link className="hover:underline" href="/">Home</Link>
            </nav>
          </div>
        </header>
        <main className="mx-auto max-w-3xl px-4 py-8">{children}</main>
        <footer className="mx-auto max-w-3xl px-4 py-10 text-sm text-neutral-500">
          Generated by your ContentGen agent.
        </footer>
      </body>
    </html>
  );
}
