name: contentgen-agent

on:
  push:
    branches: [ main ]          # auto runs on push
  workflow_dispatch:            # and can be run manually with inputs
    inputs:
      apply:   { type: boolean, default: true }
      commit:  { type: string,  default: "chore(agent): automated push" }
      branch:  { type: string,  default: "" }
      force:   { type: boolean, default: false }
      no_check:{ type: boolean, default: false }
      fix_tabs:{ type: boolean, default: true }
      tasks:   { type: string,  default: "diagnose,yaml-check,commit-push" }
      create_test_change: { type: boolean, default: true }

permissions:
  contents: write

concurrency:
  group: agent-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      APPLY:        ${{ github.event_name == 'workflow_dispatch' && inputs.apply   || 'true' }}
      COMMIT_MSG:   ${{ github.event_name == 'workflow_dispatch' && inputs.commit  || 'chore(agent): automated push' }}
      BRANCH:       ${{ github.event_name == 'workflow_dispatch' && inputs.branch  || '' }}
      FORCE:        ${{ github.event_name == 'workflow_dispatch' && inputs.force   || 'false' }}
      NO_CHECK:     ${{ github.event_name == 'workflow_dispatch' && inputs.no_check|| 'false' }}
      FIX_TABS:     ${{ github.event_name == 'workflow_dispatch' && inputs.fix_tabs|| 'true' }}
      TASKS:        ${{ github.event_name == 'workflow_dispatch' && inputs.tasks   || 'diagnose,yaml-check,commit-push' }}
      CREATE_TEST:  ${{ github.event_name == 'workflow_dispatch' && inputs.create_test_change || 'false' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install agent deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i -D yaml fast-glob

      - name: Optional test change
        if: ${{ env.CREATE_TEST == 'true' }}
        run: echo "agent ping $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> AGENT_TEST.txt

      - name: Run agent
        shell: bash
        env:
          GIT_AUTHOR_NAME: contentgen-agent
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
          GIT_COMMITTER_NAME: contentgen-agent
          GIT_COMMITTER_EMAIL: actions@users.noreply.github.com
        run: |
          set -euo pipefail
          ARGS=()
          [ "${APPLY}" = "true" ]    && ARGS+=(--apply)
          [ "${FORCE}" = "true" ]    && ARGS+=(--force)
          [ "${NO_CHECK}" = "true" ] && ARGS+=(--no-check)
          [ "${FIX_TABS}" = "true" ] && ARGS+=(--fix)
          [ -n "${BRANCH}" ]         && ARGS+=(--branch "${BRANCH}")
          ARGS+=(--commit "${COMMIT_MSG}")
          IFS=',' read -ra TS <<< "${TASKS}"
          for t in "${TS[@]}"; do ARGS+=(--task "$t"); done
          node scripts/agent.mjs "${ARGS[@]}" --push

      - name: Upload agent report
        uses: actions/upload-artifact@v4
        with:
          name: agent-report
          path: agent_reports/latest.json

      - name: Show last commits
        run: git --no-pager log --oneline -n 5
