name: contentgen-agent

on:
  push:
    branches: [ main ]     # change if you want
  workflow_dispatch:
    inputs:
      apply:   { type: boolean, default: true }
      commit:  { type: string,  default: "chore(agent): automated push" }
      branch:  { type: string,  default: "" }
      force:   { type: boolean, default: false }
      no_check:{ type: boolean, default: false }
      fix_tabs:{ type: boolean, default: true }
      create_test_change: { type: boolean, default: true }

permissions:
  contents: write

concurrency:
  group: agent-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    # Resolve values: if manual run, use inputs; else use repo variables; else fallback defaults.
    env:
      APPLY:        ${{ github.event_name == 'workflow_dispatch' && inputs.apply   || vars.AGENT_APPLY   || 'true' }}
      COMMIT_MSG:   ${{ github.event_name == 'workflow_dispatch' && inputs.commit  || vars.AGENT_COMMIT  || 'chore(agent): automated push' }}
      BRANCH:       ${{ github.event_name == 'workflow_dispatch' && inputs.branch  || vars.AGENT_BRANCH  || '' }}
      FORCE:        ${{ github.event_name == 'workflow_dispatch' && inputs.force   || vars.AGENT_FORCE   || 'false' }}
      NO_CHECK:     ${{ github.event_name == 'workflow_dispatch' && inputs.no_check|| vars.AGENT_NO_CHECK|| 'false' }}
      FIX_TABS:     ${{ github.event_name == 'workflow_dispatch' && inputs.fix_tabs|| vars.AGENT_FIX_TABS|| 'true' }}
      CREATE_TEST:  ${{ github.event_name == 'workflow_dispatch' && inputs.create_test_change || vars.AGENT_CREATE_TEST_CHANGE || 'false' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install agent deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i -D yaml fast-glob

      - name: Create test change (optional)
        if: ${{ env.CREATE_TEST == 'true' }}
        run: echo "agent ping $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> AGENT_TEST.txt

      - name: Run agent
        shell: bash
        env:
          GIT_AUTHOR_NAME: contentgen-agent
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
          GIT_COMMITTER_NAME: contentgen-agent
          GIT_COMMITTER_EMAIL: actions@users.noreply.github.com
        run: |
          set -euo pipefail
          ARGS=()
          [ "${APPLY}" = "true" ]    && ARGS+=(--apply)
          [ "${FORCE}" = "true" ]    && ARGS+=(--force)
          [ "${NO_CHECK}" = "true" ] && ARGS+=(--no-check)
          [ "${FIX_TABS}" = "true" ] && ARGS+=(--fix)
          [ -n "${BRANCH}" ]         && ARGS+=(--branch "${BRANCH}")
          ARGS+=(--commit "${COMMIT_MSG}")
          node scripts/agent.mjs "${ARGS[@]}" --push

      - name: Show last commits
        run: git --no-pager log --oneline -n 5
