name: contentgen-agent

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Actually commit and push (true/false)"
        required: false
        default: "false"
      no_check:
        description: "Skip YAML lint (true/false)"
        required: false
        default: "false"
      fix_tabs:
        description: "Auto-fix tabs/whitespace before commit (true/false)"
        required: false
        default: "true"
      commit_msg:
        description: "Commit message used when apply=true"
        required: false
        default: "chore(agent): automated run"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/agent.yml"
      - "scripts/agent.mjs"
  schedule:
    - cron: "17 5 * * *"  # daily because why not

permissions:
  contents: write

concurrency:
  group: contentgen-agent-${{ github.ref }}
  cancel-in-progress: false

jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install runtime deps for agent script
        run: |
          npm i -D yaml fast-glob

      - name: Dry run — diagnostics + YAML check
        env:
          AGENT_NO_CHECK: ${{ inputs.no_check }}
          AGENT_FIX_TABS: ${{ inputs.fix_tabs }}
        run: |
          node scripts/agent.mjs --task diagnose --task yaml-check

      - name: Commit & push (only when apply=true)
        if: ${{ inputs.apply == 'true' }}
        env:
          AGENT_NO_CHECK: ${{ inputs.no_check }}
          AGENT_FIX_TABS: ${{ inputs.fix_tabs }}
          AGENT_COMMIT_MSG: ${{ inputs.commit_msg }}
        run: |
          node scripts/agent.mjs --apply --task commit-push --commit "${AGENT_COMMIT_MSG}"
