name: contentgen-agent

on:
  workflow_dispatch:
    inputs:
      commit_msg:
        description: Commit message for the run
        required: false
        default: "chore(agent): auto-run"
        type: string
      no_check:
        description: Skip YAML validation
        required: false
        default: false
        type: boolean
      fix_tabs:
        description: Convert tabs to spaces before YAML parse
        required: false
        default: true
        type: boolean
      dry_run:
        description: Don't apply (no commit/push), just run tasks
        required: false
        default: false
        type: boolean
      extra_tasks:
        description: Comma-separated extra tasks (e.g. "diagnose,yaml-check")
        required: false
        default: ""
        type: string
  push:
  schedule:
    # daily heartbeat at 07:17 UTC, change if you like
    - cron: "17 7 * * *"

permissions:
  contents: write

# Prevent overlapping runs on the same branch
concurrency:
  group: contentgen-agent-${{ github.ref }}
  cancel-in-progress: true

jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Ensure runtime deps for agent script
        run: |
          npm i -D yaml fast-glob || true

      - name: Run agent
        env:
          # Optional deployment secrets (unused unless you wire deploy steps later)
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

          # Agent config
          AGENT_REMOTE: origin
          AGENT_BRANCH: ${{ github.ref_name }}
          AGENT_TEST_FILE: .agent_heartbeat

          # Inputs (booleans are typed in the dispatcher)
          NO_CHECK:   ${{ github.event_name == 'workflow_dispatch' && inputs.no_check || false }}
          FIX_TABS:   ${{ github.event_name == 'workflow_dispatch' && inputs.fix_tabs || true }}
          DRY_RUN:    ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
          EXTRA_TASKS:${{ github.event_name == 'workflow_dispatch' && inputs.extra_tasks || '' }}
          COMMIT_MSG: ${{ github.event_name == 'workflow_dispatch' && inputs.commit_msg || 'chore(agent): auto-run' }}
        shell: bash
        run: |
          set -euo pipefail

          git config user.name  "contentgen-agent"
          git config user.email "actions@users.noreply.github.com"

          # make sure we're on the same branch the workflow is on
          git checkout "${AGENT_BRANCH}" || true

          FLAGS=()

          # Only include --apply when not in dry-run mode
          if [[ "${DRY_RUN}" != "true" ]]; then
            FLAGS+=( --apply )
          fi

          # Core tasks
          FLAGS+=( --task write-test-change )
          FLAGS+=( --task yaml-check )
          FLAGS+=( --task commit-push )
          FLAGS+=( --commit "${COMMIT_MSG}" )

          # Optional flags
          if [[ "${NO_CHECK}" == "true" ]]; then FLAGS+=( --no-check ); fi
          if [[ "${FIX_TABS}" == "true" ]]; then FLAGS+=( --fix ); fi

          # Extra tasks passed as comma-separated list
          if [[ -n "${EXTRA_TASKS}" ]]; then
            IFS=',' read -ra T <<< "${EXTRA_TASKS}"
            for t in "${T[@]}"; do
              t_trimmed="$(echo "$t" | xargs)"
              [[ -n "${t_trimmed}" ]] && FLAGS+=( --task "${t_trimmed}" )
            done
          fi

          echo "Running agent with flags:"
          printf '  %q\n' "${FLAGS[@]}"

          node scripts/agent.mjs "${FLAGS[@]}"

      - name: Upload agent run report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-report
          path: agent_reports/latest.json
          if-no-files-found: warn
