name: contentgen-agent

on:
  # Manually runnable with inputs
  workflow_dispatch:
    inputs:
      no_check:
        description: "Skip YAML checks"
        type: boolean
        default: false
      fix_tabs:
        description: "Auto-fix tabs to spaces"
        type: boolean
        default: true
      force:
        description: "Force rebase if push is rejected"
        type: boolean
        default: false
      branch:
        description: "Target branch (blank = current)"
        type: string
        default: ""
      commit:
        description: "Commit message"
        type: string
        default: "chore(agent): automated push"

  # Optional: run when this workflow or scripts change
  push:
    paths:
      - ".github/workflows/agent.yml"
      - "scripts/**"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      # Map inputs (when manually dispatched) into env vars with sane defaults.
      NO_CHECK: ${{ github.event_name == 'workflow_dispatch' && inputs.no_check || 'false' }}
      FIX_TABS: ${{ github.event_name == 'workflow_dispatch' && inputs.fix_tabs || 'true' }}
      FORCE:   ${{ github.event_name == 'workflow_dispatch' && inputs.force   || 'false' }}
      BRANCH:  ${{ github.event_name == 'workflow_dispatch' && inputs.branch  || '' }}
      COMMIT_MSG: ${{ github.event_name == 'workflow_dispatch' && inputs.commit || 'chore(agent): automated push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install agent deps
        run: npm i -D yaml fast-glob

      - name: Run agent
        shell: bash
        run: |
          set -euo pipefail

          ARGS=()
          [[ "${NO_CHECK}" == "true" ]] && ARGS+=(--no-check)
          [[ "${FIX_TABS}" == "true" ]] && ARGS+=(--fix)
          [[ "${FORCE}"   == "true" ]] && ARGS+=(--force)
          [[ -n "${BRANCH}" ]] && ARGS+=(--branch "${BRANCH}")
          ARGS+=(--commit "${COMMIT_MSG}")

          node scripts/agent.mjs "${ARGS[@]}"

      - name: Upload agent report
        uses: actions/upload-artifact@v4
        with:
          name: agent-report
          path: agent_reports/latest.json
          if-no-files-found: ignore
