name: contentgen-agent

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply changes (commit/push). If false, dry-run only."
        type: boolean
        default: true
      commit:
        description: "Commit message"
        type: string
        default: "chore(agent): automated push"
      branch:
        description: "Branch to operate on (blank = current)"
        type: string
        default: ""
      force:
        description: "Use --force-with-lease if needed"
        type: boolean
        default: false
      no_check:
        description: "Skip YAML sanity checks"
        type: boolean
        default: false
      fix_tabs:
        description: "Convert tabs→spaces in YAML before checking"
        type: boolean
        default: true

concurrency:
  group: agent-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need history for rebase

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install agent deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i -D yaml fast-glob

      - name: Run agent
        shell: bash
        env:
          GIT_AUTHOR_NAME: contentgen-agent
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
          GIT_COMMITTER_NAME: contentgen-agent
          GIT_COMMITTER_EMAIL: actions@users.noreply.github.com
        run: |
          set -euo pipefail
          ARGS=()
          [[ "${{ inputs.apply }}" == "true" ]] && ARGS+=(--apply)
          [[ "${{ inputs.force }}" == "true" ]] && ARGS+=(--force)
          [[ "${{ inputs.no_check }}" == "true" ]] && ARGS+=(--no-check)
          [[ "${{ inputs.fix_tabs }}" == "true" ]] && ARGS+=(--fix)
          [[ -n "${{ inputs.branch }}" ]] && ARGS+=(--branch "${{ inputs.branch }}")
          [[ -n "${{ inputs.commit }}" ]] && ARGS+=(--commit "${{ inputs.commit }}")
          node scripts/agent.mjs "${ARGS[@]}" --push

      - name: Show last commits
        run: git --no-pager log --oneline -n 5
