name: contentgen

on:
  workflow_dispatch:
    inputs:
      max:
        description: "Max number of posts to generate"
        required: false
        default: "2"
  schedule:
    # M/W/F at 06:20 UTC
    - cron: "20 6 * * 1,3,5"

permissions:
  contents: write

concurrency:
  group: contentgen-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm i

      # ← NEW: self-diagnose & auto-fix (creates config/topics if missing, checks API key)
      - name: Doctor (auto-fix config/topics, verify env)
        run: node scripts/doctor.mjs --apply

      - name: Generate content
        run: |
          MAX="${{ github.event.inputs.max }}"
          if [ -z "$MAX" ]; then MAX=2; fi
          node scripts/contentgen.mjs --max "$MAX"

      - name: Commit & push (via agent, handles rebase)
        run: |
          node scripts/agent.mjs --apply --task commit-push --commit "content: auto-generate posts"
