name: contentgen

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "High-level prompt (optional)"
        required: false
        default: ""
      dry:
        description: "Dry-run (no writes/commits)"
        required: false
        default: "true"
      max:
        description: "Max items to generate"
        required: false
        default: "1"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install deps
        run: npm ci || npm i

      # IMPORTANT: ignore node_modules, .git, agent_reports etc
      - name: Fail if git conflict markers exist
        shell: bash
        run: |
          set -euo pipefail
          if grep -RIn \
               --exclude-dir=".git" \
               --exclude-dir="node_modules" \
               --exclude-dir="agent_reports" \
               --exclude-dir=".next" \
               --exclude-dir="dist" \
               -E '^(<<<<<<< |=======$|>>>>>>> )' . ; then
            echo "Conflict markers found. Fix them before merging."
            exit 1
          else
            echo "No conflict markers found."
          fi

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node scripts/contentgen.mjs \
            --prompt "${{ github.event.inputs.prompt }}" \
            --dry "${{ github.event.inputs.dry }}" \
            --max "${{ github.event.inputs.max }}"

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contentgen-report
          path: agent_reports/latest.json
          if-no-files-found: ignore
