name: contentgen

on:
  workflow_dispatch:
    inputs:
      max:
        description: "How many posts to make"
        required: false
        default: "1"
      dry:
        description: "Dry run (true/false)"
        required: false
        default: "true"
      topic:
        description: "Optional topic filter"
        required: false
  schedule:
    - cron: "17 7 * * *" # adjust as you like (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4o-mini' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Generate content
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::warning::OPENAI_API_KEY is not set; forcing dry mode."
            DRY=true
          else
            DRY="${{ inputs.dry || 'false' }}"
          fi

          MAX="${{ inputs.max || '1' }}"
          TOPIC="${{ inputs.topic || '' }}"
          EXTRA=()
          [ -n "$TOPIC" ] && EXTRA+=(--topic "$TOPIC")

          # --dry expands only if DRY is true
          node scripts/contentgen.mjs ${DRY:+--dry} --max "$MAX" "${EXTRA[@]}"

      - name: Commit & push (if any)
        shell: bash
        run: |
          git config user.name "contentgen-agent"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(content): auto-generate"
            git fetch origin main
            git pull --rebase origin main || true
            git push
          fi
