name: Deploy web

on:
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/deploy-web.yml"
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/deploy-web.yml"

permissions:
  contents: read

jobs:
  build:
    name: Build (web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npm run type-check --if-present

      - name: Build
        run: npm run build
