name: PR guard

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  conflict-markers:
    name: No conflict markers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Scan for conflict markers
        run: |
          set -e
          if git grep -n '<<<<<<<\|>>>>>>>\|=======' -- . ':!package-lock.json' ; then
            echo "::error::Conflict markers found in the files above."
            exit 1
          fi
          echo "No conflict markers found."
