name: PR guard

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  conflict-markers:
    name: No conflict markers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Scan for conflict markers
        run: |
          set -euo pipefail
          echo "Scanning for conflict markers at line start (excluding workflow files)..."
          if git grep -nE '^(<{7}|={7}|>{7})' -- ':!/.github/workflows/*.yml' HEAD; then
            echo "Conflict markers detected. Please resolve them before merging."
            exit 1
          fi
          echo "No conflict markers found."
